version: '3'

services:

  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
    ports:
      - "3306:3306"

  redis-dev:
    image: redis:latest
    ports:
      - "6379:6379"